spring:
  profiles:
    active: mvc  # "mvc" 또는 "rest"로 설정 핸들러 처리 (@Controller에서의 service를 요청해도 RestControllerAdvice의 Exception동작할 때가 있으므로 지정해서 활용)
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
  h2:
    console:
      enabled: true
#http://localhost:8080/h2-console/login.do 과 같은 형태로 접근이 가능하다.
  mybatis:
    # 매퍼 파일의 위치를 classpath:mapper/*.xml로 수정
    mapper-locations: classpath:mapper/*.xml  # 모든 매퍼 XML 파일 로드
    type-aliases-package: com.nive.prjt.nive.*.domain  # Type Aliases 설정
    configuration:
      map-underscore-to-camel-case: true
